### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by reynold1** [reconSuave/PlayboyPDF#2]
I've been using your binary program to convert my DjVu files to pdf files.

I'm able to make it through a handful of conversions before I encounter the following error consistently:

Traceback (most recent call last):
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\playboy.py", line 164, in <module>
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\playboy.py", line 156, in main
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\playboy.py", line 126, in process_file
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1065, in output
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 246, in close
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1637, in _enddoc
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1585, in _putresources
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1514, in _putimages
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1546, in _putimage
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1903, in _putstream
  File "C:\Users\DJR-PC\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1918, in _out
MemoryError

I received this error on both my desktop computer and my laptop computer.

Can you tell from the syntax what the potential problem may be?

**Comment by adidasos** [comment]
My friend is getting the same error, sometimes after only processing 1 issue, and says the first time it ran it got a few done, but now it only does 1 or 2 before quitting. He's using Windows 11, command prompt, and the exe file.

  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\playboy.py", line 164, in <module>
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\playboy.py", line 156, in main
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\playboy.py", line 126, in process_file
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1065, in output
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 246, in close
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1637, in _enddoc
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1585, in _putresources
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1514, in _putimages
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1546, in _putimage
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1904, in _putstream
  File "C:\Users\tom\AppData\Local\Temp\ONEFIL~1\fpdf\fpdf.py", line 1918, in _out
MemoryError

He removed all the files 25MB and above based on a comment on the Bondi Rolling Stones converter, it still errored on a 24MB file, however after a few hiccups he got all the files below 25MB done, around the 25MB size however the program only seems able to convert 1 file before crashing.
